spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3360/svm
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rladncjf1
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9001
